<?php
// auth-generated by ModuleConfigHandler
// date: 12/28/2020 14:08:26
define('MOD_PRODUCT_ENABLED', true);
define('MOD_PRODUCT_TITLE', 'product LaiKeTui Module');
define('MOD_PRODUCT_VERSION', 1.0);
define('MOD_PRODUCT_NAME', 'product');
define('MOD_PRODUCT_AUTHOR', 'fly');
define('MOD_PRODUCT_HOMEPAGE', null);
define('MOD_PRODUCT_UPDATE_URL', null);
define('MOD_PRODUCT_DESCRIPTION', 'product LaiKeTui Module');
?>