<?php
// auth-generated by ModuleConfigHandler
// date: 12/28/2020 14:08:47
define('MOD_PRODUCT_CLASS_ENABLED', true);
define('MOD_PRODUCT_CLASS_TITLE', 'product_class LaiKeTui Module');
define('MOD_PRODUCT_CLASS_VERSION', 1.0);
define('MOD_PRODUCT_CLASS_NAME', 'product_class');
define('MOD_PRODUCT_CLASS_AUTHOR', 'fly');
define('MOD_PRODUCT_CLASS_HOMEPAGE', null);
define('MOD_PRODUCT_CLASS_UPDATE_URL', null);
define('MOD_PRODUCT_CLASS_DESCRIPTION', 'product_class LaiKeTui Module');
?>