<?php
// auth-generated by ModuleConfigHandler
// date: 04/02/2021 11:04:48
define('MOD_PRODUCT_CONFIG_ENABLED', true);
define('MOD_PRODUCT_CONFIG_TITLE', 'product_config LaiKeTui Module');
define('MOD_PRODUCT_CONFIG_VERSION', 1.0);
define('MOD_PRODUCT_CONFIG_NAME', 'product_config');
define('MOD_PRODUCT_CONFIG_AUTHOR', 'dhb');
define('MOD_PRODUCT_CONFIG_HOMEPAGE', null);
define('MOD_PRODUCT_CONFIG_UPDATE_URL', null);
define('MOD_PRODUCT_CONFIG_DESCRIPTION', 'product_config LaiKeTui Module');
?>