<?php
// auth-generated by ModuleConfigHandler
// date: 01/25/2021 10:29:37
define('MOD_KEYWORD_ENABLED', true);
define('MOD_KEYWORD_TITLE', 'keyword LaiKeTui Module');
define('MOD_KEYWORD_VERSION', 1.0);
define('MOD_KEYWORD_NAME', 'keyword');
define('MOD_KEYWORD_AUTHOR', 'fly');
define('MOD_KEYWORD_HOMEPAGE', null);
define('MOD_KEYWORD_UPDATE_URL', null);
define('MOD_KEYWORD_DESCRIPTION', 'keyword LaiKeTui Module');
?>