<?php
// auth-generated by ModuleConfigHandler
// date: 01/18/2021 11:42:36
define('MOD_PI_ENABLED', true);
define('MOD_PI_TITLE', 'pi Module');
define('MOD_PI_VERSION', 1.0);
define('MOD_PI_NAME', 'pi');
define('MOD_PI_AUTHOR', 'ketter');
define('MOD_PI_HOMEPAGE', null);
define('MOD_PI_UPDATE_URL', null);
define('MOD_PI_DESCRIPTION', '插件后台中央集权中心，所有插件后台管理的出入口');
?>