<?php
// auth-generated by ModuleConfigHandler
// date: 12/28/2020 14:07:45
define('MOD_ADMINLOGIN_ENABLED', true);
define('MOD_ADMINLOGIN_TITLE', 'AdminLogin LaiKeTui Module');
define('MOD_ADMINLOGIN_VERSION', 1.0);
define('MOD_ADMINLOGIN_NAME', 'AdminLogin');
define('MOD_ADMINLOGIN_AUTHOR', 'fly');
define('MOD_ADMINLOGIN_HOMEPAGE', null);
define('MOD_ADMINLOGIN_UPDATE_URL', null);
define('MOD_ADMINLOGIN_DESCRIPTION', 'AdminLogin LaiKeTui Module');
?>