<?php
// auth-generated by ModuleConfigHandler
// date: 12/28/2020 14:07:43
define('MOD_LOGIN_ENABLED', true);
define('MOD_LOGIN_TITLE', 'Login LaiKeTui Module');
define('MOD_LOGIN_VERSION', 1.0);
define('MOD_LOGIN_NAME', 'Login');
define('MOD_LOGIN_AUTHOR', 'fly');
define('MOD_LOGIN_HOMEPAGE', null);
define('MOD_LOGIN_UPDATE_URL', null);
define('MOD_LOGIN_DESCRIPTION', 'Login LaiKeTui Module');
?>