<?php
// auth-generated by ModuleConfigHandler
// date: 12/28/2020 20:25:00
define('MOD_USERLIST_ENABLED', true);
define('MOD_USERLIST_TITLE', 'userlist LaiKeTui Module');
define('MOD_USERLIST_VERSION', 1.0);
define('MOD_USERLIST_NAME', 'userlist');
define('MOD_USERLIST_AUTHOR', 'fly');
define('MOD_USERLIST_HOMEPAGE', null);
define('MOD_USERLIST_UPDATE_URL', null);
define('MOD_USERLIST_DESCRIPTION', 'userlist LaiKeTui Module');
?>