<?php
// auth-generated by ModuleConfigHandler
// date: 01/18/2021 11:43:01
define('MOD_COUPON_ENABLED', true);
define('MOD_COUPON_TITLE', 'coupon LaiKeTui Module');
define('MOD_COUPON_VERSION', 1.0);
define('MOD_COUPON_NAME', 'coupon');
define('MOD_COUPON_AUTHOR', 'dhb');
define('MOD_COUPON_HOMEPAGE', null);
define('MOD_COUPON_UPDATE_URL', null);
define('MOD_COUPON_DESCRIPTION', 'coupon LaiKeTui Module');
?>