<?php
// auth-generated by ModuleConfigHandler
// date: 01/25/2021 10:32:38
define('MOD_BANNER_ENABLED', true);
define('MOD_BANNER_TITLE', 'banner LaiKeTui Module');
define('MOD_BANNER_VERSION', 1.0);
define('MOD_BANNER_NAME', 'banner');
define('MOD_BANNER_AUTHOR', 'fly');
define('MOD_BANNER_HOMEPAGE', null);
define('MOD_BANNER_UPDATE_URL', null);
define('MOD_BANNER_DESCRIPTION', 'banner LaiKeTui Module');
?>