<?php
// auth-generated by ModuleConfigHandler
// date: 01/14/2021 19:17:27
define('MOD_COMMENTS_ENABLED', true);
define('MOD_COMMENTS_TITLE', 'comments LaiKeTui Module');
define('MOD_COMMENTS_VERSION', 1.0);
define('MOD_COMMENTS_NAME', 'comments');
define('MOD_COMMENTS_AUTHOR', 'fly');
define('MOD_COMMENTS_HOMEPAGE', null);
define('MOD_COMMENTS_UPDATE_URL', null);
define('MOD_COMMENTS_DESCRIPTION', 'comments LaiKeTui Module');
?>