<?php
// auth-generated by ModuleConfigHandler
// date: 12/28/2020 14:09:17
define('MOD_RETURN_ENABLED', true);
define('MOD_RETURN_TITLE', 'return LaiKeTui Module');
define('MOD_RETURN_VERSION', 1.0);
define('MOD_RETURN_NAME', 'return');
define('MOD_RETURN_AUTHOR', 'dhb');
define('MOD_RETURN_HOMEPAGE', null);
define('MOD_RETURN_UPDATE_URL', null);
define('MOD_RETURN_DESCRIPTION', 'return LaiKeTui Module');
?>