<?php
// auth-generated by ModuleConfigHandler
// date: 03/11/2021 19:58:43
define('MOD_STOCK_ENABLED', true);
define('MOD_STOCK_TITLE', 'stock LaiKeTui Module');
define('MOD_STOCK_VERSION', 1.0);
define('MOD_STOCK_NAME', 'stock');
define('MOD_STOCK_AUTHOR', 'dhb');
define('MOD_STOCK_HOMEPAGE', null);
define('MOD_STOCK_UPDATE_URL', null);
define('MOD_STOCK_DESCRIPTION', 'stock LaiKeTui Module');
?>