<?php
// auth-generated by ModuleConfigHandler
// date: 01/28/2021 15:54:49
define('MOD_ORDERSLIST_ENABLED', true);
define('MOD_ORDERSLIST_TITLE', 'orderslist LaiKeTui Module');
define('MOD_ORDERSLIST_VERSION', 1.0);
define('MOD_ORDERSLIST_NAME', 'orderslist');
define('MOD_ORDERSLIST_AUTHOR', 'fly');
define('MOD_ORDERSLIST_HOMEPAGE', null);
define('MOD_ORDERSLIST_UPDATE_URL', null);
define('MOD_ORDERSLIST_DESCRIPTION', 'orderslist LaiKeTui Module');
?>