<?php
// auth-generated by ModuleConfigHandler
// date: 01/18/2021 11:43:01
define('MOD_PLUG_INS_ENABLED', true);
define('MOD_PLUG_INS_TITLE', 'plug_ins LaiKeTui Module');
define('MOD_PLUG_INS_VERSION', 1.0);
define('MOD_PLUG_INS_NAME', 'plug_ins');
define('MOD_PLUG_INS_AUTHOR', 'dhb');
define('MOD_PLUG_INS_HOMEPAGE', null);
define('MOD_PLUG_INS_UPDATE_URL', null);
define('MOD_PLUG_INS_DESCRIPTION', 'plug_ins LaiKeTui Module');
?>