<?php
// auth-generated by ModuleConfigHandler
// date: 02/07/2021 21:42:13
define('MOD_BRAND_CLASS_ENABLED', true);
define('MOD_BRAND_CLASS_TITLE', 'brand_class LaiKeTui Module');
define('MOD_BRAND_CLASS_VERSION', 1.0);
define('MOD_BRAND_CLASS_NAME', 'brand_class');
define('MOD_BRAND_CLASS_AUTHOR', 'fly');
define('MOD_BRAND_CLASS_HOMEPAGE', null);
define('MOD_BRAND_CLASS_UPDATE_URL', null);
define('MOD_BRAND_CLASS_DESCRIPTION', 'brand_class LaiKeTui Module');
?>